version: '3'

services:
  db:
    image: postgres
    networks:
      - exampleApp-network

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - SERVICE_PORTS=8000
    deploy:
      replicas: 10
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    depends_on:
      - db
    networks:
      - exampleApp-network

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - web
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - exampleApp-network

networks:
  exampleApp-network:
    driver: overlay